### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by krenax**
The example programs fail without these installation steps.

### CODE REVIEW

**Comment by davidmezzetti** [comment]
Hello, I appreciate the PR!

Would you mind sharing what the error was you're encountering? Installing `autoawq[kernels]` is supposed to install `autoawq-kernels`.

**Comment by krenax** [comment]
The installation returns the following.

```
Collecting flash-attn>=2.2.0
  Using cached flash_attn-2.7.2.post1.tar.gz (3.1 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-8w16qsvf/flash-attn_3fc2607ec6af40a481216e2b4a618a20/setup.py", line 11, in <module>
          from packaging.version import parse, Version
      ModuleNotFoundError: No module named 'packaging'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
``

**Comment by davidmezzetti** [comment]
I figured that was the case. I submitted this issue previously: https://github.com/casper-hansen/AutoAWQ/issues/678

And put in this PR to the upstream project to try to fix the underlying issue. https://github.com/Dao-AILab/flash-attention/pull/1380

But as of now it's not fixed. Perhaps this is a good solution. Were you sure it used the GPU without installing flash-attn?

**Comment by davidmezzetti** [comment]
There were a couple other updates regarding the install. I updated the README to include this. Thank you for submitting this issue.

**Pull request closed without merging**
